export const STRINGS = {
  sv: {
    home:'Hem', activity:'Aktivitet', plan:'Plan', goals:'Mål', more:'Mer', income:'Inkomst', remaining:'Kvar', spent:'Spenderat', saved:'Sparat', myBudget:'Min budget', recentPurchases:'Senaste köp', fixedCosts:'Fasta kostnader', notes:'Anteckningar', paydayCountdown:'Till nästa budgetcykel', investments:'Investeringar', netWorth:'Nettoförmögenhet', cashFlow:'Kassaflöde', addWidget:'Lägg till widget', viewAll:'Visa alla', addPurchase:'Lägg till köp', amount:'Belopp', category:'Kategori', date:'Datum', whatBought:'Vad köpte du?', optional:'Valfritt', note:'Anteckning', paymentAccount:'Betalsätt / konto', save:'Spara', cancel:'Avbryt', budget:'Budget', categories:'Kategorier', budgetCycle:'Budgetcykel', calendarMonth:'Kalendermånad', payday:'Lön till lön', custom:'Anpassad', savings:'Sparande', monthlySavings:'Sparlogg månad för månad', addGoal:'Nytt sparmål', target:'Målbelopp', current:'Nuvarande', dueDate:'Måldatum', theme:'Tema', language:'Språk', currency:'Valuta', settings:'Inställningar', widgetLibrary:'Widgetbibliotek', add:'Lägg till', remove:'Ta bort', pinned:'Fäst', unpin:'Lossa', edit:'Redigera', delete:'Radera', noTransactions:'Inga transaktioner ännu', onboardingTitle:'Din ekonomi. Ditt sätt.', onboardingSubtitle:'Ställ in grunden. Resten kan du ändra senare.', continue:'Fortsätt', openZayva:'Öppna ZAYVA', chooseTheme:'Välj tema', howBudget:'Hur budgeterar du?', regularIncome:'Din vanliga inkomst', chooseCategories:'Välj budgetkategorier', yourZayvaReady:'Din ZAYVA är redo.', committed:'kommande', allCategories:'Alla kategorier', name:'Namn', newCategory:'Ny kategori', transaction:'Transaktion', tapDelete:'Tryck på en transaktion för att radera den i prototypen.', confirmDelete:'Radera transaktionen?', day:'Dag', resetDemo:'Återställ demodata', resetConfirm:'Återställ ZAYVA-demon?', widgetLibraryHint:'Välj vad som förtjänar plats på Hem.', laterModule:'Förberett för en senare ZAYVA-modul.', purchase:'Köp', mainAccount:'Huvudkonto', newGoal:'Nytt mål'
  },
  en: {
    home:'Home', activity:'Activity', plan:'Plan', goals:'Goals', more:'More', income:'Income', remaining:'Remaining', spent:'Spent', saved:'Saved', myBudget:'My budget', recentPurchases:'Recent purchases', fixedCosts:'Fixed costs', notes:'Notes', paydayCountdown:'Until next budget cycle', investments:'Investments', netWorth:'Net worth', cashFlow:'Cash flow', addWidget:'Add widget', viewAll:'See all', addPurchase:'Add purchase', amount:'Amount', category:'Category', date:'Date', whatBought:'What did you buy?', optional:'Optional', note:'Note', paymentAccount:'Payment method / account', save:'Save', cancel:'Cancel', budget:'Budget', categories:'Categories', budgetCycle:'Budget cycle', calendarMonth:'Calendar month', payday:'Payday to payday', custom:'Custom', savings:'Savings', monthlySavings:'Monthly savings log', addGoal:'New savings goal', target:'Target', current:'Current', dueDate:'Target date', theme:'Theme', language:'Language', currency:'Currency', settings:'Settings', widgetLibrary:'Widget library', add:'Add', remove:'Remove', pinned:'Pin', unpin:'Unpin', edit:'Edit', delete:'Delete', noTransactions:'No transactions yet', onboardingTitle:'Your money. Your way.', onboardingSubtitle:'Set the foundation. You can change everything later.', continue:'Continue', openZayva:'Open ZAYVA', chooseTheme:'Choose theme', howBudget:'How do you budget?', regularIncome:'Your regular income', chooseCategories:'Choose budget categories', yourZayvaReady:'Your ZAYVA is ready.', committed:'upcoming', allCategories:'All categories', name:'Name', newCategory:'New category', transaction:'Transaction', tapDelete:'Tap a transaction to delete it in this prototype.', confirmDelete:'Delete the transaction?', day:'Day', resetDemo:'Reset demo data', resetConfirm:'Reset the ZAYVA demo?', widgetLibraryHint:'Choose what deserves space on Home.', laterModule:'Prepared for a later ZAYVA module.', purchase:'Purchase', mainAccount:'Main account', newGoal:'New goal'
  }
};

export function createTranslator(getState) {
  return (key) => STRINGS[getState().settings.language]?.[key] ?? STRINGS.en[key] ?? key;
}
